class StoredProcedure():
    def __init__(self):
        # self.hello = 'EXEC employee_hello'
        self.getDId = 'SELECT dId FROM DepartmentEmployee WHERE ssn = ?'
        self.updateSubject = 'EXEC UpdateSubject ?,?,?'
        self.updateTeacherOfClass = 'EXEC UpdateTeacherOfClass ?,?,?,?,?'
        self.subjectOnSemester = 'EXEC SubjectOnSemester ?,?'
        self.teacherOnSemester = 'EXEC TeacherOnSemester ?,?'
        self.classOfTeacher = 'EXEC ClassOfTeacher ?,?'
        self.teacherOfClass = 'EXEC TeacherOfClass ?,?'
        self.bookOfSubject = 'EXEC BookOfSubject ?,?'
        self.studentOfClass = 'EXEC StudentOfClass ?,?'
        self.numStudentOfSemester = 'EXEC NumStudentOfSemester ?,?'
        self.numClassOfSemester = 'EXEC NumClassOfSemester ?,?'
        self.subjectHavingMaxTeacher = 'EXEC SubjectHavingMaxTeacher ?,?'
        self.avgNumStudent = 'EXEC AvgNumStudent ?'
