class StoredProcedure():
    def __init__(self):
        # self.hello = 'EXEC employee_hello'
        self.getDId = 'SELECT dId FROM DepartmentEmployee WHERE ssn = ?'
        self.addSubject = 'EXEC addSubject ?,?,?'
        self.removeSubject = 'EXEC removeSubject ?,?,?'
        self.updateSubject = 'EXEC updateSubject ?,?,?,?'
        self.addTeacherOfClass = 'EXEC addTeacherOfClass ?,?,?,?,?'
        self.removeTeacherOfClass = 'EXEC removeTeacherOfClass ?,?,?,?,?'
        self.updateTeacherOfClass = 'EXEC updateTeacherOfClass ?,?,?,?,?,?'
        self.subjectOnSemester = 'EXEC SubjectOnSemester ?,?'
        self.teacherOnSemester = 'EXEC TeacherOnSemester ?,?'
        self.classOfTeacher = 'EXEC ClassOfTeacher ?,?'
        self.teacherOfClass = 'EXEC TeacherOfClass ?,?'
        self.bookOfSubject = 'EXEC BookOfSubject ?,?'
        self.studentOfClass = 'EXEC StudentOfClass ?,?'
        self.numStudentOfSemester = 'EXEC NumStudentOfSemester ?,?'
        self.numClassOfSemester = 'EXEC NumClassOfSemester ?,?'
        self.subjectHavingMaxTeacher = 'EXEC SubjectHavingMaxTeacher ?,?'
        self.avgNumStudent = 'EXEC AvgNumStudent ?'
        self.listSubject = 'EXEC listSubjectDE ?'
        self.listStudent = 'EXEC listStudentDE ?'
        self.listTeacher = 'EXEC listTeacherDE ?'
        self.listReferenceBook = 'EXEC listReferenceBookDE ?'
