USE Class_Registration
SELECT 'DROP PROCEDURE [' + SCHEMA_NAME(p.schema_id) + '].[' + p.NAME + '];'
FROM sys.procedures p 
DROP PROCEDURE [dbo].[addRegister];
DROP PROCEDURE [dbo].[removeRegister];
DROP PROCEDURE [dbo].[updateRegister];
DROP PROCEDURE [dbo].[registeredClass];
--DROP PROCEDURE [dbo].[responsibleClass];
--DROP PROCEDURE [dbo].[listSubject];
DROP PROCEDURE [dbo].[listTeacher];
DROP PROCEDURE [dbo].[numOfSubjects];
DROP PROCEDURE [dbo].[numOfClasses];
DROP PROCEDURE [dbo].[numOfStudents_class_sem];
DROP PROCEDURE [dbo].[numOfStudents_sub_sem];
DROP PROCEDURE [dbo].[numOfStudents_sub_dep];
DROP PROCEDURE [dbo].[addSubject];
DROP PROCEDURE [dbo].[removeSubject];
DROP PROCEDURE [dbo].[updateSubject];
DROP PROCEDURE [dbo].[addTeacherOfClass];
DROP PROCEDURE [dbo].[removeTeacherOfClass];
DROP PROCEDURE [dbo].[updateTeacherOfClass];
DROP PROCEDURE [dbo].[SubjectOnSemester];
DROP PROCEDURE [dbo].[TeacherOnSemester];
DROP PROCEDURE [dbo].[ClassOfTeacher];
DROP PROCEDURE [dbo].[TeacherOfClass];
DROP PROCEDURE [dbo].[BookOfSubject];
DROP PROCEDURE [dbo].[StudentOfClass];
DROP PROCEDURE [dbo].[NumClassOfSemester];
DROP PROCEDURE [dbo].[SubjectHavingMaxTeacher];
DROP PROCEDURE [dbo].[AvgNumStudent];
DROP PROCEDURE [dbo].[addReferenceBook];
DROP PROCEDURE [dbo].[removeReferenceBook];
DROP PROCEDURE [dbo].[updateReferenceBook];
DROP PROCEDURE [dbo].[responsibleClasses];
DROP PROCEDURE [dbo].[numOfStudents_ofResponsiblesClass];
DROP PROCEDURE [dbo].[numOfResponsibleClass_3RecentYear];
DROP PROCEDURE [dbo].[top5Class_mostStudent];
DROP PROCEDURE [dbo].[top5Semester_mostClass];
DROP PROCEDURE [dbo].[RegisterSubject];
DROP PROCEDURE [dbo].[SubjectClassTeacher];
DROP PROCEDURE [dbo].[ClassOfSubject];
DROP PROCEDURE [dbo].[ClassOfSubjectMoreThan1Teacher];
DROP PROCEDURE [dbo].[SumCredit];
DROP PROCEDURE [dbo].[SumSubject];
DROP PROCEDURE [dbo].[First3MaxCredit];
DROP PROCEDURE [dbo].[listStudent];
DROP PROCEDURE [dbo].[NumStudentOfSemester];
DROP PROCEDURE [dbo].[studentOfResopnsibleClass];
DROP PROCEDURE [dbo].[referenceBookOfResponsibleSubject];
DROP PROCEDURE [dbo].[listReferenceBook];
DROP PROCEDURE [dbo].[SubjectReferenceBook];
-- DROP PROCEDURE [dbo].[register_account];
-- DROP PROCEDURE [dbo].[login_account];

